spring.application.name=webapp
server.port = 8081

# Configuração do banco de dados no spring
spring.datasource.url=jdbc:postgresql://localhost:5432/futebolapp
spring.datasource.username=postgres
spring.datasource.password=stranger
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api.url=http://apifutebol.footstats.com.br
api.token=seu_token

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html